-- MySQL Script generated by MySQL Workbench
-- Tue Jun  9 20:16:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema saep_limpeza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema saep_limpeza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `saep_limpeza` DEFAULT CHARACTER SET utf8 ;
USE `saep_limpeza` ;

-- -----------------------------------------------------
-- Table `saep_limpeza`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saep_limpeza`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `passwd` VARCHAR(45) NULL,
  `saldo` DECIMAL(6,2) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saep_limpeza`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saep_limpeza`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NULL,
  `categoria_produto` VARCHAR(45) NULL,
  `quantidade_medida_produto` VARCHAR(45) NULL,
  `valor_quantidade_produto` DECIMAL(6,2) NULL,
  `valor_total_quantidade_produto` DECIMAL(6,2) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `usuario_idusuario`),
  INDEX `fk_produto_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_produto_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `saep_limpeza`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saep_limpeza`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saep_limpeza`.`historico` (
  `idhistorico` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  `produto_usuario_idusuario` INT NOT NULL,
  `nome_produto_historico` VARCHAR(45) NULL,
  `quantidade_medida_produto_historico` INT NULL,
  `valor_movido` DECIMAL(6,2) NULL,
  `total_movido` VARCHAR(45) NULL,
  `saldo_final` DECIMAL(6,2) NULL,
  PRIMARY KEY (`idhistorico`, `produto_idproduto`, `produto_usuario_idusuario`),
  INDEX `fk_historico_produto1_idx` (`produto_idproduto` ASC, `produto_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_historico_produto1`
    FOREIGN KEY (`produto_idproduto` , `produto_usuario_idusuario`)
    REFERENCES `saep_limpeza`.`produto` (`idproduto` , `usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE VIEW `vw_estoque` AS
SELECT `nome_produto`, `quantidade_medida_produto`, `valor_quantidade_produto`, `valor_total_quantidade_produto`
FROM produto
WHERE valor_total_quantidade_produto (quantidade_medida_produto * valor_quantidade_produto);

SELECT * FROM vw_estoque;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
